### ISSUE TITLE
Article writing

### ISSUE THREAD

**Issue by emdelponte** [openplantpathology/Reproducibility_in_Plant_Pathology#17]
@adamhsparks @grunwald @zachary-foster 

I did some work on the manuscript [Rmd file](https://github.com/phytopathology/Reproducible.Plant.Pathology/blob/master/inst/paper/What%20Does%20Reproducible%20Research%20Mean%20for%20Plant%20Pathology.Rmd) and committed the changes:

- Inserted portions of text for the abstract and introduction sections
- Made and included diagram in the text using [DiagrammeR](http://rich-iannone.github.io/DiagrammeR/) package. Anyone can make further changes and check by running the chunk. The programming of the diagram uses [Graphviz](http://rich-iannone.github.io/DiagrammeR/graphviz_and_mermaid.html) and is quite easy.
- Described three levels of reproducibility associated with the diagram
- Changed the style of the html file - the export to .doc file is not working with the diagram code and  this format was eliminated for now.  The export to html is working fine but not accessible on GitHub because the docs folder is set to pages.

**Comment by adamhsparks** [comment]
https://stackoverflow.com/questions/30307191/using-diagrammer-in-word-document-generated-using-rmarkdown#32094377

**Comment by adamhsparks** [comment]
I like it! It illustrates the idea very nicely. Thanks Emerson.

I saw your e-mail, just hadn't responded yet.

**Comment by emdelponte** [comment]
@adamhsparks  
I followed the above example on how to include the DiagrammeR image file in Word format but it is not working. It seems the PhantomJS (phantomjs.org) is not working properly on my mac after downloading and running the executable.

**Comment by adamhsparks** [comment]
OK, thanks @emdelponte, I've not tried it yet. Was working on _bomrang_ over the weekend.

I'll have a go on my Macs and see what happens.

**Comment by adamhsparks** [comment]
Fixed, can now export to MS Word and generate a PDF of the figure: https://github.com/phytopathology/Reproducible.Plant.Pathology/commit/d8778f7eb7dec7c940b949e617406290ddc2c88a

I do like the HTML page though, wonder if there's a way to do both...

**Comment by emdelponte** [comment]
Thanks @adamhsparks. Why do we need the MS Word file? the HTML file should work as our pre-print version. We could submit a PDF file of the main text to Phytopathology, together with the figures.

**Comment by zachary-foster** [comment]
Looks good! I will take a closer look today and get back to you.

**Comment by adamhsparks** [comment]
@emdelponte, 
If I'm reading this right from http://apsjournals.apsnet.org/page/authorinformation#checklist, the text file needs to be something in a test file format, not a PDF? That's why I'd like both versions, should be doable with the YAML, I've just not fussed with it yet. The Word version follows a template that I've made to output a Word document that follows the APS journals style guidelines as best I can.

> Text files can be in Word, Rich Text, or other common word processing formats.

Also my PDF figure needs to be a .tif

> Figures should be submitted in .tif, .eps, or .jpg format, with captions entered into Manuscript Central.

**Comment by emdelponte** [comment]
@adamhsparks they are more flexible about figure formats lately. In my latest submission, the figures were accepted in PNG high resolution. Your MS Word template is fine and I guess that some reviewers would like to download the MS Word file for sending comments, edits, etc. However, I suggest that our Rmd file for submission contains only the main text, not the figures, which should be in another file - we will need to submit them separately anyway.  

By the way, there are two Rmd files there: paper and the one with the article title. We need to have a new one with the main text.

**Comment by adamhsparks** [comment]
True, I don't comment in Word files when I review, but I know others do.

To your point about the figures, I'd generated the PDF of the figure separately for that reason.

I was noticing we needed to do some cleaning and maintenance in the directory with our files. Do you want to do that or should I?

**Comment by emdelponte** [comment]
You can do the cleaning work. I am still learning how you organized the repo as package. For the updated Rmd files, I suggest shorter file names though. Something like Sparks-etal-maintext.Rmd

As of figures, the `chunks` can be set to `Show nothing` and so the codes could stay there. Alternatively, to avoid lengthy files, we could place the code for the figures, tables and analyses in separate Rmd files, similar to what I did [here](https://github.com/emdelponte/paper-FHB-Brazil-meta-analysis).

**Comment by zachary-foster** [comment]
I read through what we have so far and made a few changes. I will submit a PR so you can easily see what I changed. Good start, Its nice to see the paper coming together!

**Comment by zachary-foster** [comment]
Oh, I also set up the YAML so that pdf, html, and word outputs are made if you render from the console:

```r
rmarkdown::render('What Does Reproducible Research Mean for Plant Pathology.Rmd', output_format = 'all')
```

**Comment by emdelponte** [comment]
> Good start, Its nice to see the paper coming together!

@zachary-foster  Yes, seeing it taking shape may lead us to focus on both writing and the data extraction from the papers. I want to start reading similar papers from other fields to improve introduction. I thought of definitions placed in a box instead of text paragraphs.

**Comment by adamhsparks** [comment]
Paper is mostly drafted. I'll close this now as we approach publication.
