### ISSUE TITLE
Paper categorization?

### ISSUE THREAD

**Issue by emdelponte** [openplantpathology/Reproducibility_in_Plant_Pathology#20]
@adamhsparks @grunwald @zachary-foster 

I went through my sample of 50 articles again and came up with this categorization specific to papers in plant disease-related journals. You may want to propose new ones, split or combine categories. I started with applied versus fundamental and would like your input also to check whether the subcategories are in the right category. 

The idea is to provide specific guidelines with regards reproducibility of studies in plant pathology. Is this useful?

###  Fundamental

- Basic pathogen biology
- Plant-pathogen interaction
- Pathogen population genetics
- Molecular evolution and ecology 
- Functional genomics
- Quantitative epidemiology and modeling
- New taxa (species)

### Applied

- Molecular diagnosis/survey of plant pathogens
- Disease/pathogen/metabolites survey
- Pathogen/disease report (morphology/molecular/pathogenicity)
- Experimental research (treatment effects)
- Research methods and toolbox (e.g. primer dev, selective media, software, etc)
- Screening germplasm/cultivar for resistance

**Comment by zachary-foster** [comment]
I will have to consider this as I read the other half of my articles. I dont have any modifications at the moment, but might later. Good idea; I will keep it in mind and get back to you.

**Comment by emdelponte** [comment]
Yes, and please try to assign them to these proposed categories. After ~ 30 articles I was not creating any additional subcategory. Let's wait for @adamhsparks and @grunwald comments and  then we could create a new column right after applied/fundamental for these subcategories. In a few articles, there may be a mix of two categories, but mostly will fit well one of those.

**Comment by emdelponte** [comment]
Once we agree on the categories/subcategories, I will include a column and inspect each article again. This should be associated with journal categories.
