### ISSUE TITLE
Computational tool availablility and data availability ratings

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/Reproducibility_in_Plant_Pathology#21]
Thinking back to a thread on Twitter recently, GitHub and the like are not proper repositories. Really we should be ranking availability of scripts and data the highest for being available from libraries (e.g., K-State's KREX, USQ's e-prints, etc.). Zenodo, being CERN might be top tier, but GitHub, FigShare are probably second tier.

**Comment by emdelponte** [comment]
I agree. This should be recommendation for data/script storage. I would think of Open Science Framework.
