### ISSUE TITLE
Not building the pkgdown site locally

### ISSUE THREAD

**Issue by emdelponte** [openplantpathology/Reproducibility_in_Plant_Pathology#22]
I get this error when I try to build the site. The website does not build the new Rmd file in the DOC folder.

> build_site()
Error in yaml::yaml.load(string, ...) : 
  Scanner error: while scanning a simple key at line 2, column 1 could not find expected ':' at line 3, column 1
In addition: Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/America/Sao_Paulo'

**Comment by adamhsparks** [comment]
Since this works for me on all of my machines I've tested, I suspect it's a local issue.

1. What version of R do you have installed?

2. What version of `pkgdown` do you have installed?

**Comment by adamhsparks** [comment]
@emdelponte did you ever get this sorted? It's still working fine for me.
